In [1]:
from dolfin import *
import meshio
%matplotlib inline

In [2]:
import os
os.getcwd()

'/root/stokes_flow_ice_fracture/3_our_implementation/1_workshop/1_stokes_flow_without_damage/calibration/calibration'

In [37]:
import numpy as np

In [3]:
mesh = meshio.read("Mesh_22.med")
points, cell, cell_data, field_data = mesh.points, mesh.cells, mesh.cell_data, mesh.field_data

In [4]:
# mesh = meshio.read("Mesh_1.med")
# points, cell, cell_data, field_data = mesh.points, mesh.cells, mesh.cell_data, mesh.field_data

In [5]:
cell

{'line': array([[  8,   7],
        [  9,   8],
        [ 10,   9],
        [ 11,  10],
        [ 12,  11],
        [ 13,  12],
        [ 14,  13],
        [ 15,  14],
        [ 16,  15],
        [ 17,  16],
        [ 18,  17],
        [ 19,  18],
        [ 20,  19],
        [ 21,  20],
        [ 22,  21],
        [ 23,  22],
        [ 24,  23],
        [ 25,  24],
        [ 26,  25],
        [ 27,  26],
        [ 28,  27],
        [ 29,  28],
        [ 30,  29],
        [ 31,  30],
        [ 32,  31],
        [ 33,  32],
        [ 34,  33],
        [ 35,  34],
        [ 36,  35],
        [ 37,  36],
        [ 38,  37],
        [ 39,  38],
        [ 40,  39],
        [ 41,  40],
        [ 42,  41],
        [ 43,  42],
        [ 44,  43],
        [ 45,  44],
        [ 46,  45],
        [ 47,  46],
        [ 48,  47],
        [ 49,  48],
        [ 50,  49],
        [ 51,  50],
        [ 52,  51],
        [ 53,  52],
        [ 54,  53],
        [ 55,  54],
        [ 56,  55],
        [  5

In [6]:
# cell['triangle']
# cell['tetra']
cell['tetra']

array([[10796, 10797, 11043, 11344],
       [ 1141, 10398,  1169,   966],
       [ 8952,  6193,  6077,  6194],
       ...,
       [10419,  9637,  9612,  1176],
       [13479, 18227,  9531, 18199],
       [ 3538, 13479,  3718,  9533]])

In [7]:
a = cell['tetra']

In [8]:
a

array([[10796, 10797, 11043, 11344],
       [ 1141, 10398,  1169,   966],
       [ 8952,  6193,  6077,  6194],
       ...,
       [10419,  9637,  9612,  1176],
       [13479, 18227,  9531, 18199],
       [ 3538, 13479,  3718,  9533]])

In [9]:
np.unique(mesh.point_data['point_tags'])

NameError: name 'np' is not defined

In [10]:
cell[1]

KeyError: 1

In [11]:
points[:,:]

array([[500.        , 500.        ,   0.        ],
       [500.        , 500.        , 125.        ],
       [500.        ,   0.        ,   0.        ],
       ...,
       [199.27840749, 213.47333063,  39.0573517 ],
       [200.58013909, 243.94221144,  51.8245206 ],
       [253.847248  , 246.65026812,  52.23872458]])

In [12]:
meshio.write("mesh/Mesh_3D.xdmf", meshio.Mesh(
    points=points[:,:],
    cells={"tetra": a}))

In [12]:
meshio.write("line.xdmf", meshio.Mesh(
    points=points[:,[0,2]],
    cells={"line": cell["line"]},
    cell_data={"line": {"marker": -cell_data["line"]["cell_tags"]}}
))

IndexError: index 2 is out of bounds for axis 1 with size 2

In [47]:
meshio.write("point.xdmf", meshio.Mesh(
    points= points[:,[0,2]],
    cells = {"vertex": np.array([[i,] for i in range(len(points))])},# here the cell is a vertex and the cell num is vertex num
    cell_data={"vertex":{"marker": mesh.point_data["point_tags"]}}
))

In [48]:
mesh.point_data["point_tags"].max()

3

In [49]:
mesh.cell_tags

{-6: ['load_line'], -7: ['face']}

In [50]:
mesh.point_tags

{2: ['left_support'], 3: ['right_sipport']}

In [51]:
arr=cell_data["triangle"]["cell_tags"]
num=2

In [52]:
if num in arr:
    print(True)
else:
    print(False)

False


In [53]:
np.unique(arr)

array([-7])

In [12]:
import meshio
mesh = meshio.read("mesh/notch.xml")

In [13]:
points, cell, cell_data, field_data = mesh.points, mesh.cells, mesh.cell_data, mesh.field_data

In [14]:
cell

{'triangle': array([[   1, 1523, 1524],
        [   0, 1523, 1524],
        [   1, 1524, 1528],
        ...,
        [ 402,  691, 1095],
        [ 521, 1094, 1096],
        [ 402, 1094, 1096]])}

In [15]:
cell['triangle']

array([[   1, 1523, 1524],
       [   0, 1523, 1524],
       [   1, 1524, 1528],
       ...,
       [ 402,  691, 1095],
       [ 521, 1094, 1096],
       [ 402, 1094, 1096]])

In [16]:
np.unique(mesh.point_data['point_tags'])

KeyError: 'point_tags'

In [19]:
a = cell['triangle']

In [17]:
points[:,:]

array([[240.        ,   5.        ],
       [240.        ,   0.        ],
       [245.        ,   0.        ],
       ...,
       [232.18015401,  37.5       ],
       [269.15192128,  86.76540172],
       [232.32309911,  26.82307075]])

In [20]:
meshio.write("mesh/not1.xdmf", meshio.Mesh(
    points=points[:,:],
    cells={"triangle": a}))

# Demo

In [54]:
mesh_2d = Mesh()
with XDMFFile("mesh.xdmf") as infile:
    infile.read(mesh_2d)

In [55]:
mvc = MeshValueCollection("size_t", mesh_2d, 1)
with XDMFFile("line.xdmf") as infile:
    infile.read(mvc, "marker")

mf = cpp.mesh.MeshFunctionSizet(mesh_2d, mvc)

mf.array()[mf.array()>20]=0

with XDMFFile("mesh/mesh_function.xdmf") as xdmf_outfile:
    xdmf_outfile.write(mf)

In [56]:
mf.array().max()

6

In [57]:
mvc = MeshValueCollection("size_t", mesh_2d, 0)
with XDMFFile("point.xdmf") as infile:
    infile.read(mvc, "marker")

mf = cpp.mesh.MeshFunctionSizet(mesh_2d, mvc)

mf.array()[mf.array()>20]=0

with XDMFFile("mesh/point_mesh_function.xdmf") as xdmf_outfile:
    xdmf_outfile.write(mf)

In [58]:
mf.array().max()

3

In [59]:
mvc.dim()

0